### ISSUE TITLE
I2C read data

### ISSUE THREAD

**Issue by Nikolsi** [SINTEF-9012/bglib#18]
Hello, could you show somehow an example how to get data from a specific sensor with i2c by using your library? How to get these read bytes?
Thank you in advance

**Comment by ffleurey** [comment]
Hello, I have not used it for a while but the library is only an port of the C library from BG. You should be able to find/translate from their examples and documentation. As far as I remember everything is asynchronous so when you send a "read" command you should get the result of the read (and the data) in a callback. You just have to find from the documentation which is the right callback :-) Hope this helps you get on the right track. Cheers, Franck

**Comment by Nikolsi** [comment]
Frank, Thank you for your response. I found the solution without calling any hardware fuctions.
Wish you all the best,
Nikolai

**Comment by Nikolsi** [comment]
Oh, and I have sht21 sensor with address 128bit
