### ISSUE TITLE
Binary distribution availability

### ISSUE THREAD

**Issue by bcraun** [SINTEF-9012/bglib#19]
Hello,

I'm trying to add the Maven dependency within IntelliJ with no luck. I've used various search terms including bglib-protocol, bgapi, org.thingml, etc. and nothing is available. Am I missing something?

Thanks,
Bill

**Comment by ffleurey** [comment]
Hello! The binaries are not deployed to maven central repositories but only in our thingml repository. You can set it up by adding it to your pom.xml with something like:
`

```
<repositories>
    <repository>
        <id>thingml-snapshot</id>
        <name>thingml-snapshot</name>
        <url>http://maven.thingml.org/thingml-snapshot/</url>
    </repository>

    <repository>
        <id>thingml-release</id>
        <name>thingml-release</name>
        <url>http://maven.thingml.org/thingml-release/</url>
    </repository>

    <repository>
        <id>thirdparty</id>
        <name>thingml-snapshot</name>
        <url>http://maven.thingml.org/thirdparty/</url>
    </repository>

</repositories>
```

`
With that you should be able to add the dependency with something like:

`

```
<dependency>
  <groupId>org.thingml</groupId>
  <artifactId>bglib-protocol-1.0.3-43</artifactId>
  <version>1.1.0</version>
</dependency>
```

`

Cheers,

Franck

**Comment by bcraun** [comment]
Hi Franck,

Thanks for the quick response. I appreciate your time.

Bill
