### ISSUE TITLE
bglib as a Processing 3.x library

### ISSUE THREAD

**Issue by mjs513** [SINTEF-9012/bglib#20]
Hi all.

I would like to create a executable jar file from the bglib source so I can try using it with the Proessing 3.0  environment but I have no idea how to get this done.  So if some one can tell me how to do this please let me know or if they already have a jar file and willing to share I would appreciate it.  Real newbie here to getting this accomplished.

Respectfully
Mike

**Comment by brice-morin** [comment]
Hi,

With the proper Maven plugin (that you need to insert in POM.xml), you should be able to generate a standalone executable jar. Do not remember the exact procedure, but it should be easy to find the procedure on Google.

**Comment by mjs513** [comment]
Hi bricie-morin

Finally got it compiled using the maven plugin for intelijidea. Now to try and figure out how to get use the library :)

Thanks for your help

Mike
