### ISSUE TITLE
Connection of many sensors

### ISSUE THREAD

**Issue by ruzovvo** [SINTEF-9012/bglib#5]
Hi. i'm using your api. and i want to connect multiple sensors to 1 bluegiga dongle. but i don't know how to detect(and is it possible) from which sensor data was received. Can you explain me this?

**Comment by sridharrajagopal** [comment]
Hi, 

I'm facing exactly the same issue, and I came across this post while researching the problem. I was able to successfully connect 3 devices, but when I added a 4th device to the mix, only 3 devices would connect, and the 4th attempt resulted in the rsp_gap_connect_direct result of 521. 

If anyone else has faced this issue, and/or know the solution, please let us know!

Thanks, 
Sridhar

**Comment by sridharrajagopal** [comment]
I found that the factory default setting for the dongle is a max of 3 connections. Also, the error codes are documented in the API guide - 521 = 0x0209 (Connection Limit Exceeded)

You can change the max connections in the config.xml of the configuration, recompile and reflash the dongle. Max connections supported are 8, btw.
